<a href="https://colab.research.google.com/github/william-alexandre/BigDataDeploy/blob/main/Demonstra%C3%A7%C3%A3o_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Demonstração Pandas
###Fundamentos de Big Data e Data Science

#Importar Bibliotecas

In [ ]:
import pandas as pd
import numpy as np

#Series (observe o índice do lado esquerdo)

In [ ]:
s1=pd.Series([1,2,-5,0])

In [ ]:
s1

0    1
1    2
2   -5
3    0
dtype: int64

In [ ]:
s1.values

array([ 1,  2, -5,  0])

In [ ]:
s1.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
s1

0    1
1    2
2   -5
3    0
dtype: int64

In [ ]:
s2=pd.Series([1,2,-5,0], index=['a','b', 'c', 'd'])

In [ ]:
s2

a    1
b    2
c   -5
d    0
dtype: int64

In [ ]:
s2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
s2['a']=1000

In [ ]:
s2

a    1000
b       2
c      -5
d       0
dtype: int64

#Comparação

In [ ]:
s2[s2>0]

a    1000
b       2
dtype: int64

#Algebra

In [ ]:
s3 = s2*2

In [ ]:
s3

a    2000
b       4
c     -10
d       0
dtype: int64

In [ ]:
s2

a    1000
b       2
c      -5
d       0
dtype: int64

In [ ]:
s2[s2.isnull()] = 0

#Dataframe

#Criar Dataframe

In [ ]:
dados={'estado':['SP', 'MG','PR','SP','MG','PR'],
       'ano':[2019, 2019,2019, 2020,2020,2020],
       'pop':[45.9, 21.2,16.9,46.6,21.4,17.3]}
df1=pd.DataFrame(dados)

In [ ]:
print(dados)

{'estado': ['SP', 'MG', 'PR', 'SP', 'MG', 'PR'], 'ano': [2019, 2019, 2019, 2020, 2020, 2020], 'pop': [45.9, 21.2, 16.9, 46.6, 21.4, 17.3]}

In [ ]:
df1

  estado   ano   pop
0     SP  2019  45.9
1     MG  2019  21.2
2     PR  2019  16.9
3     SP  2020  46.6
4     MG  2020  21.4
5     PR  2020  17.3

In [ ]:
df1.head(3)

  estado   ano   pop
0     SP  2019  45.9
1     MG  2019  21.2
2     PR  2019  16.9

#Visualizar partes Dataframe

In [ ]:
df1.tail(2)

  estado   ano   pop
4     MG  2020  21.4
5     PR  2020  17.3

In [ ]:
df1.sample(2)

  estado   ano   pop
2     PR  2019  16.9
3     SP  2020  46.6

#Novo DF a partir o anterior (veja as colunas)

In [ ]:
df2=pd.DataFrame(dados,columns=['ano', 'pop','estado'])

In [ ]:
df2

    ano   pop estado
0  2019  45.9     SP
1  2019  21.2     MG
2  2019  16.9     PR
3  2020  46.6     SP
4  2020  21.4     MG
5  2020  17.3     PR

#Observar DF

In [ ]:
df2['pop']

0    45.9
1    21.2
2    16.9
3    46.6
4    21.4
5    17.3
Name: pop, dtype: float64

In [ ]:
s7=pd.Series(df2['pop'])

In [ ]:
s7

0    45.9
1    21.2
2    16.9
3    46.6
4    21.4
5    17.3
Name: pop, dtype: float64

In [ ]:
s7[s7>21]

0    45.9
1    21.2
3    46.6
4    21.4
Name: pop, dtype: float64

In [ ]:
df2.estado

0    SP
1    MG
2    PR
3    SP
4    MG
5    PR
Name: estado, dtype: object

In [ ]:
df2.dtypes

ano         int64
pop       float64
estado     object
dtype: object

#Atribuir Valores

In [ ]:
df2['estimativa']= df2['pop'] * 3

In [ ]:
df2

    ano   pop estado  estimativa
0  2019  45.9     SP       137.7
1  2019  21.2     MG        63.6
2  2019  16.9     PR        50.7
3  2020  46.6     SP       139.8
4  2020  21.4     MG        64.2
5  2020  17.3     PR        51.9

In [ ]:
df2['estimativa']=np.arange(6)

In [ ]:
df2

    ano   pop estado  estimativa
0  2019  45.9     SP           0
1  2019  21.2     MG           1
2  2019  16.9     PR           2
3  2020  46.6     SP           3
4  2020  21.4     MG           4
5  2020  17.3     PR           5

In [ ]:
df3=df2

In [ ]:
df3

    ano   pop estado  estimativa
0  2019  45.9     SP           0
1  2019  21.2     MG           1
2  2019  16.9     PR           2
3  2020  46.6     SP           3
4  2020  21.4     MG           4
5  2020  17.3     PR           5

In [ ]:
df3=df2['ano']

In [ ]:
df3

0    2019
1    2019
2    2019
3    2020
4    2020
5    2020
Name: ano, dtype: int64

In [ ]:
df2['Não Paraná']= df2.estado != 'PR'

In [ ]:
df2

    ano   pop estado  estimativa  Não Paraná
0  2019  45.9     SP           0        True
1  2019  21.2     MG           1        True
2  2019  16.9     PR           2       False
3  2020  46.6     SP           3        True
4  2020  21.4     MG           4        True
5  2020  17.3     PR           5       False

#Excluir Coluna

In [ ]:
del df2['Não Paraná']

In [ ]:
df2

    ano   pop estado  estimativa
0  2019  45.9     SP           0
1  2019  21.2     MG           1
2  2019  16.9     PR           2
3  2020  46.6     SP           3
4  2020  21.4     MG           4
5  2020  17.3     PR           5

#Entender o DataFrame

In [ ]:
df2.shape

(6, 4)

In [ ]:
df2.shape[1]

4

In [ ]:
df2.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
df2.columns

Index(['ano', 'pop', 'estado', 'estimativa'], dtype='object')

In [ ]:
df2.count()

ano           6
pop           6
estado        6
estimativa    6
dtype: int64

#Alterar Informação das Colunas

In [ ]:
df2.columns=['Ano','Pop','Estado','estimativa']

In [ ]:
df2

    Ano   Pop Estado  estimativa
0  2019  45.9     SP           0
1  2019  21.2     MG           1
2  2019  16.9     PR           2
3  2020  46.6     SP           3
4  2020  21.4     MG           4
5  2020  17.3     PR           5

#Analisar o DataFrame

In [ ]:
df2.describe(include='all')

                Ano        Pop Estado  estimativa
count      6.000000   6.000000      6    6.000000
unique          NaN        NaN      3         NaN
top             NaN        NaN     SP         NaN
freq            NaN        NaN      2         NaN
mean    2019.500000  28.216667    NaN    2.500000
std        0.547723  14.096725    NaN    1.870829
min     2019.000000  16.900000    NaN    0.000000
25%     2019.000000  18.275000    NaN    1.250000
50%     2019.500000  21.300000    NaN    2.500000
75%     2020.000000  39.775000    NaN    3.750000
max     2020.000000  46.600000    NaN    5.000000

#Alterar valores e  consultar dados

In [ ]:
df2['Ano']=df2['Ano']+2

In [ ]:
df2

    Ano   Pop Estado  estimativa
0  2023  45.9     SP           0
1  2023  21.2     MG           1
2  2023  16.9     PR           2
3  2024  46.6     SP           3
4  2024  21.4     MG           4
5  2024  17.3     PR           5

In [ ]:
df2[df2['Ano']>2021]

    Ano   Pop Estado  estimativa
0  2023  45.9     SP           0
1  2023  21.2     MG           1
2  2023  16.9     PR           2
3  2024  46.6     SP           3
4  2024  21.4     MG           4
5  2024  17.3     PR           5

In [ ]:
df4=df2[df2['Ano']>2021]

In [ ]:
df4

    Ano   Pop Estado  estimativa
0  2023  45.9     SP           0
1  2023  21.2     MG           1
2  2023  16.9     PR           2
3  2024  46.6     SP           3
4  2024  21.4     MG           4
5  2024  17.3     PR           5

#Excluir Colunas

In [ ]:
df4.drop('Ano', axis='columns')

    Pop Estado  estimativa
0  45.9     SP           0
1  21.2     MG           1
2  16.9     PR           2
3  46.6     SP           3
4  21.4     MG           4
5  17.3     PR           5

In [ ]:
df4

    Ano   Pop Estado  estimativa
0  2023  45.9     SP           0
1  2023  21.2     MG           1
2  2023  16.9     PR           2
3  2024  46.6     SP           3
4  2024  21.4     MG           4
5  2024  17.3     PR           5

In [ ]:
df4

    Ano   Pop Estado  estimativa
0  2023  45.9     SP           0
1  2023  21.2     MG           1
2  2023  16.9     PR           2
3  2024  46.6     SP           3
4  2024  21.4     MG           4
5  2024  17.3     PR           5

In [ ]:
df2

    Ano   Pop Estado  estimativa
0  2023  45.9     SP           0
1  2023  21.2     MG           1
2  2023  16.9     PR           2
3  2024  46.6     SP           3
4  2024  21.4     MG           4
5  2024  17.3     PR           5

In [ ]:
df2.drop('Ano', axis='columns', inplace=True)

In [ ]:
df2

    Pop Estado  estimativa
0  45.9     SP           0
1  21.2     MG           1
2  16.9     PR           2
3  46.6     SP           3
4  21.4     MG           4
5  17.3     PR           5

#Excluir Linhas

In [ ]:
df2.drop([0,1])

    Pop Estado  estimativa
2  16.9     PR           2
3  46.6     SP           3
4  21.4     MG           4
5  17.3     PR           5

In [ ]:
df2

    Pop Estado  estimativa
2  16.9     PR           2
3  46.6     SP           3
4  21.4     MG           4
5  17.3     PR           5

###Observe a propagação na exclusão definitiva

In [ ]:
dflinhas=df2

In [ ]:
dflinhas.drop([0,1],inplace=True)

In [ ]:
dflinhas

    Pop Estado  estimativa
2  16.9     PR           2
3  46.6     SP           3
4  21.4     MG           4
5  17.3     PR           5

In [ ]:
df2

    ano   pop estado
2  2019  16.9     PR
3  2020  46.6     SP
4  2020  21.4     MG
5  2020  17.3     PR

#Ver Dados de linhas

In [ ]:
df2.iloc[2]

ano       2020
pop       21.4
estado      MG
Name: 4, dtype: object

In [ ]:
df2.iloc[1:4]

    ano   pop estado
3  2020  46.6     SP
4  2020  21.4     MG
5  2020  17.3     PR

In [ ]:
df2.iloc[1:3,[1,2]]

    pop estado
3  46.6     SP
4  21.4     MG

In [ ]:
df2

    ano   pop estado
2  2019  16.9     PR
3  2020  46.6     SP
4  2020  21.4     MG
5  2020  17.3     PR